apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deployment
  namespace: default
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
      tier: frontend
  template:
    metadata:
      labels:
        app: maven-app
        tier: frontend
    spec: # Pod spec
      containers:
        - name: my-container
          image: guyhaliva/myapp:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myconfigmapv1.0
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m" # 50 milli cores (1/20 CPU)
            limits:
              memory: "128Mi" # 128 mebibytes
              cpu: "100m"
