apiVersion: v1
kind: Service
metadata:
  name: maven-app
  namespace: default
  labels:
    app: maven-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: maven-app
    tier: frontend
  type: NodePort
