services:
  myapp:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "java", "-version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
