# Default values for myapp
replicaCount: 1

image:
  repository: guyhaliva/myapp # This should match your Docker image name
  tag: latest # Update this to match your image tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080 # Update this to match your application port

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
